module.exports = {
	AWAY:    'AWAY',
	CAP:     'CAP',
	ERROR:   'ERROR',
	JOIN:    'JOIN',
	MODE:    'MODE',
	NICK:    'NICK',
	NOTICE:  'NOTICE',
	OPER:    'OPER',
	PART:    'PART',
	PASS:    'PASS',
	PING:    'PING',
	PONG:    'PONG',
	PRIVMSG: 'PRIVMSG',
	QUIT:    'QUIT',
	RESTART: 'RESTART',
	TOPIC:   'TOPIC',
	USER:    'USER',
	WHO:     'WHO',
	WHOIS:   'WHOIS',
	WHOWAS:  'WHOWAS'
};
