
module.exports = {
	RPL_WELCOME:          'RPL_WELCOME',
	RPL_YOURHOST:         'RPL_YOURHOST',
	RPL_CREATED:          'RPL_CREATED',
	RPL_MYINFO:           'RPL_MYINFO',

	RPL_BOUNCE:           'RPL_BOUNCE',
	RPL_ISUPPORT:         'RPL_ISUPPORT',

	RPL_STATSDLINE:       'RPL_STATSDLINE',

	RPL_LUSERCLIENT:      'RPL_LUSERCLIENT',
	RPL_LUSEROP:          'RPL_LUSEROP',

	RPL_LUSERUNKNOWN:     'RPL_LUSERUNKNOWN',

	RPL_LUSERCHANNELS:    'RPL_LUSERCHANNELS',
	RPL_LUSERME:          'RPL_LUSERME',

	RPL_LOCALUSERS:       'RPL_LOCALUSERS',
	RPL_GLOBALUSERS:      'RPL_GLOBALUSERS',

	RPL_AWAY:             'RPL_AWAY',
	RPL_USERHOST:         'RPL_USERHOST',

	RPL_WHOISUSER:        'RPL_WHOISUSER',
	RPL_WHOISSERVER:      'RPL_WHOISSERVER',
	RPL_WHOISIDLE:        'RPL_WHOISIDLE',
	RPL_ENDOFWHOIS:       'RPL_ENDOFWHOIS',
	RPL_WHOISCHANNELS:    'RPL_WHOISCHANNELS',

	RPL_CHANNEL_URL:      'RPL_CHANNEL_URL',

	RPL_WHOISACCOUNT:     'RPL_WHOISACCOUNT',

	RPL_NOTOPIC:          'RPL_NOTOPIC',
	RPL_TOPIC:            'RPL_TOPIC',
	RPL_TOPICWHOTIME:     'RPL_TOPICWHOTIME',

	RPL_NAMREPLY:         'RPL_NAMREPLY',

	RPL_ENDOFNAMES:       'RPL_ENDOFNAMES',

	RPL_MOTD:             'RPL_MOTD',

	RPL_MOTDSTART:        'RPL_MOTDSTART',
	RPL_ENDOFMOTD:        'RPL_ENDOFMOTD',

	ERR_NOSUCHNICK:       'ERR_NOSUCHNICK',
	ERR_NOSUCHSERVER:     'ERR_NOSUCHSERVER',
	ERR_NOSUCHCHANNEL:    'ERR_NOSUCHCHANNEL',

	ERR_UNKNOWNCOMMAND:   'ERR_UNKNOWNCOMMAND',

	ERR_NOMOTD:           'ERR_NOMOTD',

	ERR_NONICKNAMEGIVEN:  'ERR_NONICKNAMEGIVEN',
	ERR_ERRONEUSNICKNAME: 'ERR_ERRONEUSNICKNAME',
	ERR_NICKNAMEINUSE:    'ERR_NICKNAMEINUSE',

	ERR_NOTONCHANNEL:     'ERR_NOTONCHANNEL',

	ERR_NOTIMPLEMENTED:   'ERR_NOTIMPLEMENTED',

	ERR_NOTREGISTERED:    'ERR_NOTREGISTERED',

	ERR_NEEDMOREPARAMS:   'ERR_NEEDMOREPARAMS',

	ERR_ALREADYREGISTRED: 'ERR_ALREADYREGISTRED',

	ERR_LINKCHANNEL:      'ERR_LINKCHANNEL',

	ERR_CHANNELISFULL:    'ERR_CHANNELISFULL',

	ERR_UNKNOWNMODE:      'ERR_UNKNOWNMODE',

	ERR_INVITEONLYCHAN:   'ERR_INVITEONLYCHAN',

	ERR_NEEDREGGEDNICK:   'ERR_NEEDREGGEDNICK',
	ERR_NOCHANMODES:      'ERR_NOCHANMODES',

	ERR_NOPRIVILEGES:     'ERR_NOPRIVILEGES',

	ERR_UMODEUNKNOWNFLAG: 'ERR_UMODEUNKNOWNFLAG',

	ERR_USERSDONTMATCH:   'ERR_USERSDONTMATCH'

};

