CMD-CAP     = "???"
CMD-JOIN    = "0" / ( <channel-name> *("," <channel-name>) [<channel-key> *("," <channel-key>)] )
CMD-MODE    = ( <channel-name> / <nickname> ) ( *<mode-change> / <mode-query> )
CMD-NICK    = <nickname> [ <hop-count> ]
CMD-NOTICE  = <message-target> *( "," <message-target> ) " :" <message-body>
CMD-PART    = <channel-name> *("," <channel-name>)
CMD-PASS    = <password>
CMD-PING    = <server-name> [ <server-name> ]
CMD-PONG    = <server-name> [ <server-name> ]
CMD-PRIVMSG = <message-target> *( "," <message-target> ) " :" <message-body>
CMD-QUIT    = [ <quit-message> ]
CMD-TOPIC   = <channel-name> [ <topic> ]
CMD-USER    = <user> <mode-bitmask> "*" <realname>
CMD-WHO     = [ <mask> [ <operator-flag> ] ]
CMD-WHOIS   = [ <server-name> ] <mask> *( "," <mask> )
CMD-WHOWAS = [ <server-name> ] <mask> *( "," <mask> )
