RPL-WELCOME           = "Welcome to the Internet Relay Network " <user-id>
RPL-YOURHOST          = "Your host is " <server-name> ", running version " <server-version>
RPL-CREATED           = "This server was created " <date>
RPL-MYINFO            = <server-name> " " <server-version> " " 1*<user-mode> " " 1*<channel-mode>
RPL-BOUNCE            = "Try server " <server-name> ", port " <port>
RPL-I-SUPPORT         = <settings-string> " :are supported by this server"
RPL-TRACELINK         = "???"
				      ; "Link <version & debug level> <destination>
                      ; <next server> V<protocol version>
                      ; <link uptime in seconds> <backstream sendq>
                      ; <upstream sendq>"
RPL-STATSDLINE        = ":Highest connection count: " <connection-count> " (" <client-count> " clients) (" <connection-count> " connections received)"
RPL-LUSERCLIENT       = ":There are " <user-count> " users and " <service-count> " services on " <server-count> " servers"
RPL-LUSEROP           = <operator-count> " :operator(s) online"
RPL-LUSERUNKNOWN      = <connection-count> " :unknown connection(s)"
RPL-LUSERCHANNELS     = <channel-count> " :channels formed"
RPL-LUSERME           = ":I have " <client-count> " clients and " <server-count> " servers"
RPL-LOCALUSERS        = <user-count> <user-count> " :Current local users " <user-count> ", max " <user-count>
RPL-GLOBALUSERS       = <user-count> <user-count> " :Current global users " <user-count> ", max " <user-count>
RPL-ADMINME           = <server-name> " :Administrative info"
RPL-ADMINLOC1         = ":" <admin-info>
RPL-ADMINLOC2         = ":" <admin-info>
RPL-ADMINEMAIL        = ":" <admin-info>
RPL-TRACELOG          = "File " <logfile> "." <debug-level>
RPL-TRACEEND          = <server-name> " " <server-version> "." <debug-level> " :End of TRACE"
RPL-TRYAGAIN          = <command> " :Please wait a while and try again."
RPL-AWAY              = <nick> " :" <away-message>
RPL-USERHOST          = ":" [ <userhost-reply> ] *( " " <userhost-reply> )
RPL-ISON              = ":" [ <nick> ] *( " " <nick> )
RPL-UNAWAY            = ":You are no longer marked as being away"
RPL-NOWAWAY           = ":You have been marked as being away"
RPL-WHOISUSER         = <nick> " " <user> " " <host> " * :" <realname>
RPL-WHOISSERVER       = <nick> " " <server-name> " :" <server-info>
RPL-WHOISOPERATOR     = <nick> " :is an IRC operator"
RPL-WHOWASUSER        = <nick> " " <user> " " <host> " * :" <realname>
RPL-ENDOFWHO          = <name> " :End of WHO list"
RPL-WHOISIDLE         = <nick> " " <integer> " :seconds idle"
RPL-ENDOFWHOIS        = <nick> " :End of WHOIS list"
RPL-WHOISCHANNELS     = <nick> " :" *( <nick-channel> " " )
RPL-CHANNEL-URL       = <channel-name> " :" <channel-url>
RPL-WHOISACCOUNT      = <nick> " " <auth-name> " :is logged in as"
RPL-LIST              = <channel-name> " " <integer> " :" <topic>
RPL-LISTEND           = ":End of LIST"
RPL-CHANNELMODEIS     = <channel-name> " " <mode> " " <mode-params>
RPL-UNIQOPIS          = <channel-name> " " <nick>
RPL-NOTOPIC           = <channel-name> " :No topic is set"
RPL-TOPIC             = <channel-name> " :" <channel-topic>
RPL-TOPICWHOTIME      = <channel-name> " " (<user-id> / <nick>) " " <timestamp>
RPL-INVITING          = <channel-name> " " <nick>
RPL-SUMMONING         = <user> " :Summoning user to IRC"
RPL-INVITELIST        = <channel-name> " " <invitemask>
RPL-ENDOFINVITELIST   = <channel-name> " :End of channel invite list"
RPL-EXCEPTLIST        = <channel-name> " " <exceptionmask>
RPL-ENDOFEXCEPTLIST   = <channel-name> " :End of channel exception list"
RPL-VERSION           = <server-version> "." <debug-level> " " <server-name> " :"<comments>
RPL-WHOREPLY          = <channel-name> " " <user> " " <host> " " <server-name> " " <nick> " " ( "H" / "G" / ["*"] ) [ ( "@" / "+" ) ] " :" <hopcount> " " <realname>
RPL-NAMREPLY          = <channel-privacy> " " <channel-name> " :" <channel-nick> *( " " <channel-nick>)
RPL-LINKS             = <mask> " " <server-name> " :" <hopcount> " " <server-info>
RPL-ENDOFLINKS        = <mask> " :End of LINKS list"
RPL-ENDOFNAMES        = <channel-name> " :End of NAMES list"
RPL-BANLIST           = <channel-name> " " <banmask>
RPL-ENDOFBANLIST      = <channel-name> " :End of channel ban list"
RPL-ENDOFWHOWAS       = <nick> " :End of WHOWAS"
RPL-INFO              = ":" <string>
RPL-MOTD              = ":- " <motd-text>
RPL-ENDOFINFO         = ":End of INFO list"
RPL-MOTDSTART         = ":- " <server-name> " Message of the day - "
RPL-ENDOFMOTD         = ":End of MOTD command"
RPL-YOUREOPER         = ":You are now an IRC operator"
RPL-REHASHING         = <config-file> " :Rehashing"
RPL-YOURESERVICE      = "You are service " <service-name>
RPL-TIME              = <server-name> " :" <server-time>
RPL-USERSSTART        = ":UserID   Terminal  Host"
RPL-USERS             = ":" <username> " " <ttyline> " " <hostname>
RPL-ENDOFUSERS        = ":End of users"
RPL-NOUSERS           = ":Nobody logged in"
ERR-NOSUCHNICK        = ( <nick> / <channel> )" :No such nick/channel"
ERR-NOSUCHSERVER      = <server-name> " :No such server"
ERR-NOSUCHCHANNEL     = <channel-name> " :No such channel"
ERR-CANNOTSENDTOCHAN  = <channel-name> " :Cannot send to channel"
ERR-TOOMANYCHANNELS   = <channel-name> " :You have joined too many channels"
ERR-WASNOSUCHNICK     = <nick> " :There was no such nickname"
ERR-TOOMANYTARGETS    = <target> " :" <error-code> " recipients. " <abort-message>
ERR-NOSUCHSERVICE     = <service-name> " :No such service"
ERR-NOORIGIN          = ":No origin specified"
ERR-NORECIPIENT       = ":No recipient given (" <command> ")"
ERR-NOTEXTTOSEND      = ":No text to send"
ERR-NOTOPLEVEL        = <mask> " :No toplevel domain specified"
ERR-WILDTOPLEVEL      = <mask> " :Wildcard in toplevel domain"
ERR-BADMASK           = <mask> " :Bad Server/host mask"
ERR-UNKNOWNCOMMAND    = <command> " :Unknown command"
ERR-NOMOTD            = ":MOTD File is missing"
ERR-NOADMININFO       = <server-name> " :No administrative info available"
ERR-FILEERROR         = ":File error doing " <file-op> " on " <file>
ERR-NONICKNAMEGIVEN   = ":No nickname given"
ERR-ERRONEUSNICKNAME  = <nick> " :Erroneous nickname"
ERR-NICKNAMEINUSE     = <nick> " :Nickname is already in use"
ERR-NICKCOLLISION     = <nick> " :Nickname collision KILL from " <user> "@" <host>
ERR-UNAVAILRESOURCE   = ( <nick> / <channel-name> ) " :Nick/channel is temporarily unavailable"
ERR-USERNOTINCHANNEL  = <nick> " " <channel-name> " :They aren't on that channel"
ERR-NOTONCHANNEL      = <channel-name> " :You're not on that channel"
ERR-NOTIMPLEMENTED    = ":Not yet implemented: " <text>
ERR-USERONCHANNEL     = <user> " " <channel-name> " :is already on channel"
ERR-NOLOGIN           = <user> " :User not logged in"
ERR-SUMMONDISABLED    = ":SUMMON has been disabled"
ERR-USERSDISABLED     = ":USERS has been disabled"
ERR-NOTREGISTERED     = ":You have not registered"
ERR-NEEDMOREPARAMS    = <command> " :Not enough parameters"
ERR-LINKCHANNEL       = <channel-name> " " <channel-name> " :Forwarding to another channel"
ERR-ALREADYREGISTRED  = ":Unauthorized command (already registered)"
ERR-NOPERMFORHOST     = ":Your host isn't among the privileged"
ERR-PASSWDMISMATCH    = ":Password incorrect"
ERR-YOUREBANNEDCREEP  = ":You are banned from this server"
ERR-YOUWILLBEBANNED   = "???"
ERR-KEYSET            = <channel-name> " :Channel key already set"
ERR-CHANNELISFULL     = <channel-name> " :Cannot join channel (+l)"
ERR-UNKNOWNMODE       = <mode-char> " :is unknown mode char to me for " <channel-name>
ERR-NEEDREGGEDNICK    = <channel-name> " :Cannot join channel (+r)"
ERR-INVITEONLYCHAN    = <channel-name> " :Cannot join channel (+i)"
ERR-BANNEDFROMCHAN    = <channel-name> " :Cannot join channel (+b)"
ERR-BADCHANNELKEY     = <channel-name> " :Cannot join channel (+k)"
ERR-BADCHANMASK       = <channel-name> " :Bad Channel Mask"
ERR-NOCHANMODES       = <channel-name> " :Channel doesn't support modes"
ERR-BANLISTFULL       = <channel-name> " " <char> " :Channel list is full"
ERR-NOPRIVILEGES      = ":Permission Denied- You're not an IRC operator"
ERR-CHANOPRIVSNEEDED  = <channel-name> " :You're not channel operator"
ERR-CANTKILLSERVER    = ":You can't kill a server!"
ERR-RESTRICTED        = ":Your connection is restricted!"
ERR-UNIQOPPRIVSNEEDED = ":You're not the original channel operator"
ERR-NOOPERHOST        = ":No O-lines for your host"
ERR-UMODEUNKNOWNFLAG  = ":Unknown MODE flag"
ERR-USERSDONTMATCH    = ":Cannot change mode for other users"
